#!/usr/bin/env python3

import rospy

import sys
sys.path.insert(0, '/home/sergio/ros_ws/src/utec/src/functions')
from ur5e_params import *
from ur_kinematics_functions import *

np.set_printoptions(suppress=True)

# Initialize the node
rospy.init_node("test_fkine_real")

# Initial configuration
#q0  = np.array([-0.00022919813208766016, -1.369984606955811, 1.370000145669704, -1.569999603672814, -1.5700003038388193, 2.297068376400091e-06])
q0 = np.radians(np.array([90.0,-90.0,90.0,-90.0,-90.0,0.0]))
print(q0)

# Resulting initial pose (end effector with respect to the base link)
T = fkine(q0,l)
p0 = TF2xyzquat(T)
print(p0)

xd = np.array([-0.0464, -0.7516,  0.325])
q_ikine = ikine(xd,q0,l)
print(q_ikine)
